### ISSUE TITLE
Add AWS PHP SDK into composer.json and update vendor and publish new docker image

### ISSUE THREAD

**Issue by tdondich** [ProcessMaker/docker-executor-php#3]
AWS SDK is a popular SDK we should bundle into our default executor.  Let's include it and republish a new docker image for use.

**Comment by Cievoloth** [comment]
this will be addressed here 
https://processmaker.atlassian.net/browse/KR-8165

**Comment by Cievoloth** [comment]
https://github.com/ProcessMaker/docker-executor-php/pull/4

**Comment by Cievoloth** [comment]
This is done!
